//! Allocation-free ELF64 validation and load planning for user processes.

use crate::address_space::{USER_REGION_END,USER_REGION_START};
const ELF_HEADER_SIZE:usize=64;const PROGRAM_HEADER_SIZE:usize=56;const PT_LOAD:u32=1;const PF_X:u32=1;const PF_W:u32=2;const EM_X86_64:u16=62;const ET_EXEC:u16=2;const MAX_SEGMENTS:usize=8;
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum ElfError{Truncated,BadMagic,UnsupportedClass,UnsupportedEndian,UnsupportedMachine,UnsupportedType,BadHeaderSize,BadProgramHeaders,TooManySegments,InvalidSegment,WritableExecutable,OutsideUserRegion,OverlappingSegments,EntryNotExecutable}
#[derive(Clone,Copy,Debug,Default,PartialEq,Eq)]pub struct LoadSegment{pub file_offset:u64,pub virtual_address:u64,pub file_size:u64,pub memory_size:u64,pub writable:bool,pub executable:bool}
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub struct LoadPlan{pub entry:u64,segments:[LoadSegment;MAX_SEGMENTS],count:usize}impl LoadPlan{pub fn segments(&self)->&[LoadSegment]{&self.segments[..self.count]}}
pub fn validate(image:&[u8])->Result<LoadPlan,ElfError>{if image.len()<ELF_HEADER_SIZE{return Err(ElfError::Truncated)}if &image[..4]!=b"\x7fELF"{return Err(ElfError::BadMagic)}if image[4]!=2{return Err(ElfError::UnsupportedClass)}if image[5]!=1{return Err(ElfError::UnsupportedEndian)}if le16(image,16)?!=ET_EXEC{return Err(ElfError::UnsupportedType)}if le16(image,18)?!=EM_X86_64{return Err(ElfError::UnsupportedMachine)}if le16(image,52)?as usize!=ELF_HEADER_SIZE{return Err(ElfError::BadHeaderSize)}let entry=le64(image,24)?;let phoff=usize::try_from(le64(image,32)?).map_err(|_|ElfError::BadProgramHeaders)?;let size=le16(image,54)?as usize;let count=le16(image,56)?as usize;if size!=PROGRAM_HEADER_SIZE{return Err(ElfError::BadProgramHeaders)}let end=phoff.checked_add(count.checked_mul(size).ok_or(ElfError::BadProgramHeaders)?).ok_or(ElfError::BadProgramHeaders)?;if end>image.len(){return Err(ElfError::BadProgramHeaders)}let mut plan=LoadPlan{entry,segments:[LoadSegment::default();MAX_SEGMENTS],count:0};for index in 0..count{let h=&image[phoff+index*size..phoff+(index+1)*size];if le32(h,0)?!=PT_LOAD{continue}if plan.count==MAX_SEGMENTS{return Err(ElfError::TooManySegments)}let flags=le32(h,4)?;let file_offset=le64(h,8)?;let virtual_address=le64(h,16)?;let file_size=le64(h,32)?;let memory_size=le64(h,40)?;let alignment=le64(h,48)?;if file_size>memory_size||memory_size==0||(alignment!=0&&!alignment.is_power_of_two()){return Err(ElfError::InvalidSegment)}if file_offset.checked_add(file_size).ok_or(ElfError::InvalidSegment)?>image.len()as u64{return Err(ElfError::InvalidSegment)}let memory_end=virtual_address.checked_add(memory_size).ok_or(ElfError::InvalidSegment)?;if virtual_address<USER_REGION_START||memory_end>USER_REGION_END||memory_end<=virtual_address{return Err(ElfError::OutsideUserRegion)}let writable=flags&PF_W!=0;let executable=flags&PF_X!=0;if writable&&executable{return Err(ElfError::WritableExecutable)}let segment=LoadSegment{file_offset,virtual_address,file_size,memory_size,writable,executable};for previous in &plan.segments[..plan.count]{let previous_end=previous.virtual_address+previous.memory_size;if virtual_address<previous_end&&previous.virtual_address<memory_end{return Err(ElfError::OverlappingSegments)}}plan.segments[plan.count]=segment;plan.count+=1;}if !plan.segments().iter().any(|s|s.executable&&entry>=s.virtual_address&&entry<s.virtual_address+s.memory_size){return Err(ElfError::EntryNotExecutable)}Ok(plan)}
fn le16(d:&[u8],o:usize)->Result<u16,ElfError>{let b=d.get(o..o+2).ok_or(ElfError::Truncated)?;Ok(u16::from_le_bytes([b[0],b[1]]))}fn le32(d:&[u8],o:usize)->Result<u32,ElfError>{let b=d.get(o..o+4).ok_or(ElfError::Truncated)?;Ok(u32::from_le_bytes(b.try_into().unwrap()))}fn le64(d:&[u8],o:usize)->Result<u64,ElfError>{let b=d.get(o..o+8).ok_or(ElfError::Truncated)?;Ok(u64::from_le_bytes(b.try_into().unwrap()))}

#[cfg(any(feature="m0-smoke",feature="elf-smoke"))]
pub fn test_image()->[u8;144]{let mut image=[0u8;144];image[..6].copy_from_slice(b"\x7fELF\x02\x01");image[16..18].copy_from_slice(&ET_EXEC.to_le_bytes());image[18..20].copy_from_slice(&EM_X86_64.to_le_bytes());image[24..32].copy_from_slice(&USER_REGION_START.to_le_bytes());image[32..40].copy_from_slice(&64u64.to_le_bytes());image[52..54].copy_from_slice(&64u16.to_le_bytes());image[54..56].copy_from_slice(&56u16.to_le_bytes());image[56..58].copy_from_slice(&1u16.to_le_bytes());image[64..68].copy_from_slice(&PT_LOAD.to_le_bytes());image[68..72].copy_from_slice(&PF_X.to_le_bytes());image[72..80].copy_from_slice(&120u64.to_le_bytes());image[80..88].copy_from_slice(&USER_REGION_START.to_le_bytes());image[96..104].copy_from_slice(&13u64.to_le_bytes());image[104..112].copy_from_slice(&32u64.to_le_bytes());image[112..120].copy_from_slice(&4096u64.to_le_bytes());image[120..133].copy_from_slice(&[0xb8,2,0,0,0,0xbf,37,0,0,0,0x0f,0x05,0x0f]);image}
#[cfg(feature="m0-smoke")]pub fn smoke_test(){let mut image=test_image();let plan=validate(&image).unwrap();assert_eq!(plan.segments().len(),1);image[68..72].copy_from_slice(&(PF_X|PF_W).to_le_bytes());assert_eq!(validate(&image),Err(ElfError::WritableExecutable));crate::serial::info(format_args!("m1-smoke: ELF64 validation W^X BSS passed"));}
