//! Small read-only FAT32 filesystem for the AlohaOS shell and file syscalls.
use crate::{framebuffer,sync::IrqSpinLock,virtio_blk};
#[derive(Clone,Copy)]struct Volume{sectors_per_cluster:u32,reserved_sectors:u32,fat_count:u32,sectors_per_fat:u32,root_cluster:u32,fat_start:u32,data_start:u32}
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub struct FileLocation{pub first_cluster:u32,pub size:u32}impl FileLocation{pub const EMPTY:Self=Self{first_cluster:0,size:0};}static VOLUME:IrqSpinLock<Option<Volume>>=IrqSpinLock::new(None);
pub fn init()->bool{let mut s=[0u8;512];if !virtio_blk::read_sector(0,&mut s)||s[510]!=0x55||s[511]!=0xaa{return false}let b=le16(&s,11);let spc=s[13]as u32;let res=le16(&s,14)as u32;let fc=s[16]as u32;let spf=le32(&s,36);let root=le32(&s,44);if b!=512||spc==0||spf==0||root<2{return false}*VOLUME.lock()=Some(Volume{sectors_per_cluster:spc,reserved_sectors:res,fat_count:fc,sectors_per_fat:spf,root_cluster:root,fat_start:res,data_start:res+fc*spf});true}pub fn is_mounted()->bool{VOLUME.lock().is_some()}fn vol()->Option<Volume>{*VOLUME.lock()}
pub fn lookup(name:&[u8])->Option<FileLocation>{let v=vol()?;let t=short(name)?;let mut out=None;walk(v,|e|{if e[..11]==t&&e[11]&0x10==0{out=Some(FileLocation{first_cluster:(le16(e,20)as u32)<<16|le16(e,26)as u32,size:le32(e,28)});true}else{false}});out}
pub fn read_at(l:&FileLocation,off:u32,out:&mut[u8])->usize{let Some(v)=vol()else{return 0};if out.is_empty()||off>=l.size||l.first_cluster<2{return 0}let cb=v.sectors_per_cluster*512;let mut c=l.first_cluster;let mut skip=off/cb;while skip>0{let Some(n)=next(v,c)else{return 0};if n<2||n>=0x0fff_fff8{return 0}c=n;skip-=1}let want=out.len().min((l.size-off)as usize);let mut within=off%cb;let mut done=0;let mut s=[0u8;512];while done<want&&c>=2&&c<0x0fff_fff8{let first=sector(v,c);let si=within/512;let sb=within%512;for i in si..v.sectors_per_cluster{if done==want{break}if !virtio_blk::read_sector((first+i)as u64,&mut s){return done}let start=if i==si{sb as usize}else{0};let n=(want-done).min(512-start);out[done..done+n].copy_from_slice(&s[start..start+n]);done+=n}if done==want{break}within=0;let Some(n)=next(v,c)else{break};c=n}done}
pub fn list_root(){if let Some(v)=vol(){walk(v,|e|{name_out(e);if e[11]&0x10!=0{framebuffer::write_text("/")}framebuffer::write_byte(b'\n');false})}else{framebuffer::write_line("FAT32 NOT MOUNTED")}}
pub fn cat(n:&[u8]){let Some(v)=vol()else{framebuffer::write_line("FAT32 NOT MOUNTED");return};let Some(l)=lookup(n)else{framebuffer::write_line("FILE NOT FOUND");return};let mut c=l.first_cluster;let mut rem=l.size;let mut s=[0u8;512];while c>=2&&c<0x0fff_fff8&&rem>0{let f=sector(v,c);for i in 0..v.sectors_per_cluster{if !virtio_blk::read_sector((f+i)as u64,&mut s){return}let n=rem.min(512)as usize;for&b in&s[..n]{framebuffer::write_byte(b)}rem-=n as u32;if rem==0{break}}c=next(v,c).unwrap_or(0x0fff_ffff)}}
fn walk(v:Volume,mut f:impl FnMut(&[u8;32])->bool){let mut c=v.root_cluster;let mut s=[0u8;512];for _ in 0..128{let first=sector(v,c);for i in 0..v.sectors_per_cluster{if !virtio_blk::read_sector((first+i)as u64,&mut s){return}for raw in s.chunks_exact(32){if raw[0]==0{return}if raw[0]==0xe5||raw[11]==0x0f||raw[11]&8!=0{continue}let e: &[u8;32]=raw.try_into().unwrap();if f(e){return}}}let Some(n)=next(v,c)else{return};if n>=0x0fff_fff8{return}c=n}}
fn next(v:Volume,c:u32)->Option<u32>{let o=c*4;let mut s=[0u8;512];virtio_blk::read_sector((v.fat_start+o/512)as u64,&mut s).then(||le32(&s,(o%512)as usize)&0x0fff_ffff)}fn sector(v:Volume,c:u32)->u32{v.data_start+(c-2)*v.sectors_per_cluster}fn name_out(e:&[u8;32]){for&b in&e[..11]{if b!=b' '{framebuffer::write_byte(b)}}}fn short(n:&[u8])->Option<[u8;11]>{let mut o=[b' ';11];let mut i=0;let mut ext=8;let mut dot=false;for&b in n{if b==b'.'{if dot{return None}dot=true;continue}if !b.is_ascii_alphanumeric()&&b!=b'_'{return None}if dot{if ext==11{return None}o[ext]=b.to_ascii_uppercase();ext+=1}else{if i==8{return None}o[i]=b.to_ascii_uppercase();i+=1}}(i>0).then_some(o)}fn le16(d:&[u8],o:usize)->u16{u16::from_le_bytes([d[o],d[o+1]])}fn le32(d:&[u8],o:usize)->u32{u32::from_le_bytes([d[o],d[o+1],d[o+2],d[o+3]])}
