//! AlohaOS kernel entry point.
#![no_std]
#![no_main]
extern crate alloc;
use alloc::{boxed::Box,string::String,vec::Vec};use common::BootInfo;use core::panic::PanicInfo;
mod address_space;mod backtrace;mod elf;mod fat32;mod font;mod framebuffer;mod gdt;mod handle;mod heap;mod interrupts;mod keyboard;mod memory;mod paging;mod pic;mod process;mod process_runtime;mod process_table;mod scheduler;mod serial;mod shell;mod smoke;mod spawn;mod supervisor;mod sync;mod syscall;mod syscall_arch;mod syscall_entry;mod task_context;mod task_stacks;mod timer;mod user_mode;mod virtio_blk;
#[no_mangle]pub extern "sysv64" fn _start(boot_info:*const BootInfo)->!{unsafe{core::arch::asm!("cli",options(nomem,nostack))};unsafe{serial::init()};serial::info(format_args!("AlohaOS kernel entry"));let info=unsafe{&*boot_info};framebuffer::init(info.framebuffer);framebuffer::clear(0x0f,0x17,0x2a);gdt::init();interrupts::init();if !syscall_arch::init(){fatal("SYSCALL MSR CONFIGURATION FAILED")}unsafe{memory::init(info.memory_map)};let f=memory::allocate_frame().unwrap_or_else(||fatal("NO USABLE PHYSICAL MEMORY"));let paging=match paging::init(info.memory_map){Ok(v)=>v,Err(paging::PagingError::OutOfFrames)=>fatal("PAGE TABLE ALLOCATION FAILED"),Err(paging::PagingError::PhysicalAddressTooLarge)=>fatal("PHYSICAL MEMORY EXCEEDS DIRECT MAP")};if !paging::verify_direct_map(f){fatal("HIGHER HALF DIRECT MAP TEST FAILED")}heap::init().unwrap_or_else(||fatal("KERNEL HEAP ALLOCATION FAILED"));let b=Box::new(1u64);let v=Vec::from([1u64,2,3]);let s=String::from("ALLOC");core::hint::black_box((&b,&v,&s,paging.pml4_physical));drop((s,v,b));#[cfg(feature="m0-smoke")]elf::smoke_test();smoke::run_nonfatal();#[cfg(feature="exception-smoke")]smoke::trigger_exception();#[cfg(feature="ring3-smoke")]smoke::run_ring3();#[cfg(feature="syscall-smoke")]smoke::run_syscall();#[cfg(feature="elf-smoke")]smoke::run_elf();#[cfg(feature="spawn-smoke")]smoke::run_spawn();#[cfg(feature="user-ud-smoke")]smoke::run_user_ud();#[cfg(feature="user-nx-smoke")]smoke::run_user_nx();#[cfg(feature="user-write-code-smoke")]smoke::run_user_write_code();#[cfg(feature="user-stack-guard-smoke")]smoke::run_user_stack_guard();#[cfg(feature="user-bad-pointer-smoke")]smoke::run_user_bad_pointer();#[cfg(feature="user-resume-smoke")]smoke::run_user_resume();if !task_stacks::init(){fatal("TASK STACK MAPPING FAILED")}let block=virtio_blk::init();let fat=block&&fat32::init();serial::info(format_args!("storage: virtio_blk={}, fat32={}",block,fat));scheduler::init();unsafe{pic::init_timer_and_keyboard();timer::init();}interrupts::enable();serial::info(format_args!("interrupts enabled, starting shell"));shell::run()}
fn fatal(message:&str)->!{unsafe{core::arch::asm!("cli",options(nomem,nostack))};serial::error(format_args!("fatal: {}",message));framebuffer::panic_header(message);backtrace::dump_current();halt()}
pub fn halt()->!{loop{unsafe{core::arch::asm!("hlt",options(nomem,nostack))};}}
#[panic_handler]fn panic(info:&PanicInfo)->!{unsafe{core::arch::asm!("cli",options(nomem,nostack))};serial::emergency(format_args!("panic: {}",info));framebuffer::panic_header("RUST KERNEL PANIC");backtrace::dump_current();halt()}
