//! Bounded process registry with sleep deadlines and blocking wait notifications.
use crate::{process::ProcessState,sync::IrqSpinLock};const MAX_PROCESSES:usize=64;const NO_PID:u64=0;const NO_DEADLINE:u64=u64::MAX;
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub struct ProcessRecord{pub pid:u64,pub parent:u64,pub state:ProcessState,pub exit_code:i32,pub wake_tick:u64,pub waiting_for:u64,pub wake_pending:bool}impl ProcessRecord{const EMPTY:Self=Self{pid:NO_PID,parent:NO_PID,state:ProcessState::Exited,exit_code:0,wake_tick:NO_DEADLINE,waiting_for:NO_PID,wake_pending:false};}
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum TableError{Full,AlreadyExists,NoSuchProcess,NotChild,StillRunning,InvalidDeadline}
struct ProcessTable{records:[ProcessRecord;MAX_PROCESSES],next_pid:u64}impl ProcessTable{const EMPTY:Self=Self{records:[ProcessRecord::EMPTY;MAX_PROCESSES],next_pid:1};fn allocate_pid(&mut self)->u64{loop{let p=self.next_pid.max(1);self.next_pid=p.wrapping_add(1).max(1);if !self.records.iter().any(|r|r.pid==p){return p}}}fn empty_slot(&self)->Result<usize,TableError>{self.records.iter().position(|r|r.pid==NO_PID).ok_or(TableError::Full)}}
static TABLE:IrqSpinLock<ProcessTable>=IrqSpinLock::new(ProcessTable::EMPTY);
const fn new_record(pid:u64,parent:Option<u64>)->ProcessRecord{ProcessRecord{pid,parent:match parent{Some(v)=>v,None=>0},state:ProcessState::Ready,exit_code:0,wake_tick:NO_DEADLINE,waiting_for:NO_PID,wake_pending:false}}
fn validate_parent(t:&ProcessTable,p:Option<u64>)->Result<(),TableError>{if let Some(pid)=p{if !t.records.iter().any(|r|r.pid==pid){return Err(TableError::NoSuchProcess)}}Ok(())}
fn find_mut(t:&mut ProcessTable,pid:u64)->Result<&mut ProcessRecord,TableError>{t.records.iter_mut().find(|r|r.pid==pid).ok_or(TableError::NoSuchProcess)}
pub fn spawn(parent:Option<u64>)->Result<u64,TableError>{let mut t=TABLE.lock();validate_parent(&t,parent)?;let s=t.empty_slot()?;let pid=t.allocate_pid();t.records[s]=new_record(pid,parent);Ok(pid)}
pub fn register(pid:u64,parent:Option<u64>)->Result<(),TableError>{if pid==0{return Err(TableError::NoSuchProcess)}let mut t=TABLE.lock();if t.records.iter().any(|r|r.pid==pid){return Err(TableError::AlreadyExists)}validate_parent(&t,parent)?;let s=t.empty_slot()?;t.records[s]=new_record(pid,parent);if t.next_pid<=pid{t.next_pid=pid.saturating_add(1).max(1)}Ok(())}
pub fn set_state(pid:u64,state:ProcessState)->Result<(),TableError>{let mut t=TABLE.lock();find_mut(&mut t,pid)?.state=state;Ok(())}
pub fn sleep_until(pid:u64,now:u64,deadline:u64)->Result<(),TableError>{if deadline<=now{return Err(TableError::InvalidDeadline)}let mut t=TABLE.lock();let r=find_mut(&mut t,pid)?;r.state=ProcessState::Sleeping;r.wake_tick=deadline;r.wake_pending=false;Ok(())}
pub fn advance_time(now:u64)->usize{let mut t=TABLE.lock();let mut n=0;for r in &mut t.records{if r.pid!=0&&r.state==ProcessState::Sleeping&&r.wake_tick<=now{r.state=ProcessState::Ready;r.wake_tick=NO_DEADLINE;r.wake_pending=true;n+=1}}n}
pub fn wait_blocking(parent:u64,child:u64)->Result<Option<i32>,TableError>{let mut t=TABLE.lock();let c=t.records.iter().copied().find(|r|r.pid==child).ok_or(TableError::NoSuchProcess)?;if c.parent!=parent{return Err(TableError::NotChild)}if c.state==ProcessState::Exited||c.state==ProcessState::Faulted{let status=c.exit_code;*find_mut(&mut t,child)?=ProcessRecord::EMPTY;return Ok(Some(status))}let p=find_mut(&mut t,parent)?;p.state=ProcessState::Sleeping;p.waiting_for=child;p.wake_pending=false;Ok(None)}
pub fn exit(pid:u64,code:i32)->Result<(),TableError>{let mut t=TABLE.lock();{let r=find_mut(&mut t,pid)?;r.state=ProcessState::Exited;r.exit_code=code;r.wake_tick=NO_DEADLINE;}for w in &mut t.records{if w.pid!=0&&w.waiting_for==pid{w.state=ProcessState::Ready;w.waiting_for=0;w.wake_pending=true}}Ok(())}
pub fn fault(pid:u64,code:i32)->Result<(),TableError>{exit(pid,code)?;let mut t=TABLE.lock();find_mut(&mut t,pid)?.state=ProcessState::Faulted;Ok(())}
pub fn take_wake(pid:u64)->Result<bool,TableError>{let mut t=TABLE.lock();let r=find_mut(&mut t,pid)?;let p=r.wake_pending;r.wake_pending=false;Ok(p)}
pub fn lookup(pid:u64)->Option<ProcessRecord>{TABLE.lock().records.iter().copied().find(|r|r.pid==pid)}
pub fn wait(parent:u64,child:u64)->Result<i32,TableError>{match wait_blocking(parent,child)?{Some(s)=>Ok(s),None=>Err(TableError::StillRunning)}}
pub fn orphan_children(parent:u64)->usize{let mut t=TABLE.lock();let mut n=0;for r in &mut t.records{if r.pid!=0&&r.parent==parent{r.parent=0;n+=1}}n}
#[cfg(any(feature="m0-smoke",feature="user-ud-smoke",feature="user-nx-smoke"))]pub fn reset_for_smoke(){*TABLE.lock()=ProcessTable::EMPTY;}
