//! Scheduler staging layer with complete lifecycle diagnostics.
//!
//! Extended context structures remain available for development, but cross-task
//! switching is gated off after hardware testing exposed a double fault. The
//! timer keeps the stable bootstrap task running while we redesign the low-level
//! trampoline and add a dedicated interrupt stack for scheduler transitions.

use core::sync::atomic::{AtomicU64,AtomicU8,Ordering};
const TASK_COUNT:usize=2;const NO_WAKE_DEADLINE:u64=u64::MAX;
static PREEMPTION_TICKS:AtomicU64=AtomicU64::new(0);static STATES:[AtomicU8;TASK_COUNT]=[AtomicU8::new(TaskState::Running as u8),AtomicU8::new(TaskState::Blocked as u8)];static WAKE_TICKS:[AtomicU64;TASK_COUNT]=[AtomicU64::new(NO_WAKE_DEADLINE),AtomicU64::new(NO_WAKE_DEADLINE)];static SWITCHES:[AtomicU64;TASK_COUNT]=[AtomicU64::new(0),AtomicU64::new(0)];
#[derive(Clone,Copy,Debug,PartialEq,Eq)]#[repr(u8)]pub enum TaskState{Ready=0,Running=1,Blocked=2,Sleeping=3,Dead=4}impl TaskState{fn from_raw(v:u8)->Self{match v{0=>Self::Ready,1=>Self::Running,2=>Self::Blocked,3=>Self::Sleeping,4=>Self::Dead,_=>Self::Dead}}}
#[derive(Clone,Copy)]pub struct TaskSnapshot{pub id:usize,pub state:TaskState,pub switches:u64,pub wake_tick:Option<u64>}
pub fn init(){PREEMPTION_TICKS.store(0,Ordering::Relaxed);STATES[0].store(TaskState::Running as u8,Ordering::Release);STATES[1].store(TaskState::Blocked as u8,Ordering::Release);for t in 0..TASK_COUNT{WAKE_TICKS[t].store(NO_WAKE_DEADLINE,Ordering::Relaxed);SWITCHES[t].store(0,Ordering::Relaxed)}}
pub fn state(t:usize)->Option<TaskState>{STATES.get(t).map(|v|TaskState::from_raw(v.load(Ordering::Acquire)))}pub fn wake(t:usize)->bool{transition(t,TaskState::Blocked,TaskState::Ready)||transition(t,TaskState::Sleeping,TaskState::Ready)}pub fn block(t:usize)->bool{if let Some(v)=WAKE_TICKS.get(t){v.store(NO_WAKE_DEADLINE,Ordering::Relaxed)}transition(t,TaskState::Ready,TaskState::Blocked)||transition(t,TaskState::Running,TaskState::Blocked)}pub fn sleep_until(t:usize,w:u64)->bool{let Some(d)=WAKE_TICKS.get(t)else{return false};let c=transition(t,TaskState::Ready,TaskState::Sleeping)||transition(t,TaskState::Running,TaskState::Sleeping);if c{d.store(w,Ordering::Release)}c}pub fn exit(t:usize)->bool{let Some(s)=STATES.get(t)else{return false};loop{let c=TaskState::from_raw(s.load(Ordering::Acquire));if c==TaskState::Dead{return false}if s.compare_exchange_weak(c as u8,TaskState::Dead as u8,Ordering::AcqRel,Ordering::Acquire).is_ok(){WAKE_TICKS[t].store(NO_WAKE_DEADLINE,Ordering::Release);return true}}}fn transition(t:usize,f:TaskState,n:TaskState)->bool{let Some(s)=STATES.get(t)else{return false};s.compare_exchange(f as u8,n as u8,Ordering::AcqRel,Ordering::Acquire).is_ok()}
#[no_mangle]pub extern "C" fn scheduler_on_timer_tick(stack:u64,tick:u64)->u64{PREEMPTION_TICKS.fetch_add(1,Ordering::Relaxed);SWITCHES[0].fetch_add(1,Ordering::Relaxed);for t in 0..TASK_COUNT{if state(t)==Some(TaskState::Sleeping)&&WAKE_TICKS[t].load(Ordering::Acquire)<=tick{let _=transition(t,TaskState::Sleeping,TaskState::Ready);WAKE_TICKS[t].store(NO_WAKE_DEADLINE,Ordering::Release)}}stack}
pub fn snapshots()->[TaskSnapshot;TASK_COUNT]{core::array::from_fn(|id|{let d=WAKE_TICKS[id].load(Ordering::Acquire);TaskSnapshot{id,state:state(id).unwrap_or(TaskState::Dead),switches:SWITCHES[id].load(Ordering::Relaxed),wake_tick:(d!=NO_WAKE_DEADLINE).then_some(d)}})}pub fn heartbeat()->u64{PREEMPTION_TICKS.load(Ordering::Relaxed)}pub fn worker_heartbeat()->u64{0}pub fn context_switching_ready()->bool{false}
