//! AlohaOS shell with fixed-size command history.

use crate::{framebuffer,heap,keyboard::{self,Key},memory,pic,timer};
const COMMAND_CAPACITY:usize=128;const HISTORY_CAPACITY:usize=16;
#[derive(Clone,Copy)]struct HistoryEntry{data:[u8;COMMAND_CAPACITY],length:usize}impl HistoryEntry{const EMPTY:Self=Self{data:[0;COMMAND_CAPACITY],length:0};}
struct History{entries:[HistoryEntry;HISTORY_CAPACITY],next:usize,count:usize,depth:usize}impl History{const fn new()->Self{Self{entries:[HistoryEntry::EMPTY;HISTORY_CAPACITY],next:0,count:0,depth:0}}fn push(&mut self,value:&[u8]){if value.is_empty(){self.depth=0;return}let entry=&mut self.entries[self.next];entry.data=[0;COMMAND_CAPACITY];entry.data[..value.len()].copy_from_slice(value);entry.length=value.len();self.next=(self.next+1)%HISTORY_CAPACITY;self.count=(self.count+1).min(HISTORY_CAPACITY);self.depth=0}fn up(&mut self)->Option<HistoryEntry>{if self.depth<self.count{self.depth+=1}if self.depth==0{None}else{Some(self.entries[(self.next+HISTORY_CAPACITY-self.depth)%HISTORY_CAPACITY])}}fn down(&mut self)->Option<HistoryEntry>{if self.depth>1{self.depth-=1;Some(self.entries[(self.next+HISTORY_CAPACITY-self.depth)%HISTORY_CAPACITY])}else{self.depth=0;Some(HistoryEntry::EMPTY)}}}

pub fn run()->!{banner();let mut command=[0u8;COMMAND_CAPACITY];let mut length=0usize;let mut history=History::new();loop{while let Some(scancode)=keyboard::pop_scancode(){let Some(key)=keyboard::decode(scancode)else{continue};match key{Key::Enter=>{framebuffer::write_byte(b'\n');history.push(trim(&command[..length]));execute(&command[..length]);command=[0;COMMAND_CAPACITY];length=0;prompt()},Key::Backspace=>{if length>0{length-=1;framebuffer::write_byte(8)}},Key::Character(byte)=>{if length<COMMAND_CAPACITY{command[length]=byte.to_ascii_lowercase();length+=1;framebuffer::write_byte(byte)}},Key::Up=>{if let Some(entry)=history.up(){replace_line(&mut command,&mut length,entry)}},Key::Down=>{if let Some(entry)=history.down(){replace_line(&mut command,&mut length,entry)}}}}unsafe{core::arch::asm!("sti","hlt",options(nomem,nostack))}}}
fn replace_line(command:&mut[u8;COMMAND_CAPACITY],length:&mut usize,entry:HistoryEntry){while *length>0{*length-=1;framebuffer::write_byte(8)}command.fill(0);command[..entry.length].copy_from_slice(&entry.data[..entry.length]);*length=entry.length;for&byte in&command[..*length]{framebuffer::write_byte(byte)}}
fn accent(){framebuffer::set_color(0x36,0xc5,0xf0)}fn banner(){framebuffer::clear_console();accent();framebuffer::write_line("ALOHAOS SHELL");framebuffer::set_color(0xd7,0xe0,0xee);framebuffer::write_line("TYPE HELP FOR COMMANDS");framebuffer::write_line("");prompt()}fn prompt(){accent();framebuffer::write_text("ALOHA> ");framebuffer::set_color(255,255,255)}
fn execute(raw:&[u8]){match trim(raw){b""=>{},b"help"=>framebuffer::write_line("HELP CLEAR MEMINFO UPTIME REBOOT"),b"clear"=>{framebuffer::clear_console();accent();framebuffer::write_line("ALOHAOS SHELL")},b"meminfo"=>meminfo(),b"uptime"=>uptime(),b"reboot"=>{framebuffer::write_line("REBOOTING");pic::reboot()},_=>{framebuffer::set_color(255,0x80,0x80);framebuffer::write_line("UNKNOWN COMMAND");framebuffer::set_color(255,255,255)}}}
fn meminfo(){let frames=memory::stats();let heap=heap::stats();framebuffer::write_label_dec("PHYSICAL TOTAL KB: ",frames.total_usable*4);framebuffer::write_label_dec("PHYSICAL FREE KB:  ",frames.free*4);framebuffer::write_label_dec("PHYSICAL USED KB:  ",frames.allocated*4);framebuffer::write_label_dec("HEAP SIZE KB:      ",(heap.size/1024)as u64);framebuffer::write_label_dec("HEAP USED BYTES:   ",heap.used as u64);framebuffer::write_label_dec("HEAP FREE BYTES:   ",heap.free as u64);framebuffer::write_label_dec("DROPPED KEYS:      ",keyboard::dropped_scancodes()as u64)}
fn uptime(){framebuffer::write_label_dec("UPTIME SECONDS: ",timer::seconds());framebuffer::write_label_dec("CENTISECONDS:   ",timer::centiseconds())}
fn trim(mut value:&[u8])->&[u8]{while value.first()==Some(&b' '){value=&value[1..]}while value.last()==Some(&b' '){value=&value[..value.len()-1]}value}
