//! AlohaOS shell with history, filesystem, clock and scheduler diagnostics.

use crate::{fat32,framebuffer,heap,keyboard::{self,Key},memory,pic,process_table,scheduler,spawn,timer,user_mode,virtio_blk};
const COMMAND_CAPACITY:usize=128;const HISTORY_CAPACITY:usize=16;const MAX_SHELL_IMAGE:usize=4096;
#[derive(Clone,Copy)]struct HistoryEntry{data:[u8;COMMAND_CAPACITY],length:usize}impl HistoryEntry{const EMPTY:Self=Self{data:[0;COMMAND_CAPACITY],length:0};}
struct History{entries:[HistoryEntry;HISTORY_CAPACITY],next:usize,count:usize,depth:usize}impl History{const fn new()->Self{Self{entries:[HistoryEntry::EMPTY;HISTORY_CAPACITY],next:0,count:0,depth:0}}fn push(&mut self,value:&[u8]){if value.is_empty(){self.depth=0;return}let entry=&mut self.entries[self.next];entry.data=[0;COMMAND_CAPACITY];entry.data[..value.len()].copy_from_slice(value);entry.length=value.len();self.next=(self.next+1)%HISTORY_CAPACITY;self.count=(self.count+1).min(HISTORY_CAPACITY);self.depth=0}fn up(&mut self)->Option<HistoryEntry>{if self.depth<self.count{self.depth+=1}if self.depth==0{None}else{Some(self.entries[(self.next+HISTORY_CAPACITY-self.depth)%HISTORY_CAPACITY])}}fn down(&mut self)->Option<HistoryEntry>{if self.depth>1{self.depth-=1;Some(self.entries[(self.next+HISTORY_CAPACITY-self.depth)%HISTORY_CAPACITY])}else{self.depth=0;Some(HistoryEntry::EMPTY)}}}
pub fn run()->!{banner();let mut command=[0u8;COMMAND_CAPACITY];let mut length=0;let mut history=History::new();loop{while let Some(scan)=keyboard::pop_scancode(){let Some(key)=keyboard::decode(scan)else{continue};match key{Key::Enter=>{framebuffer::write_byte(b'\n');history.push(trim(&command[..length]));execute(&command[..length]);command=[0;COMMAND_CAPACITY];length=0;prompt()},Key::Backspace=>if length>0{length-=1;framebuffer::write_byte(8)},Key::Character(byte)=>if length<COMMAND_CAPACITY{command[length]=byte.to_ascii_lowercase();length+=1;framebuffer::write_byte(byte)},Key::Up=>if let Some(entry)=history.up(){replace(&mut command,&mut length,entry)},Key::Down=>if let Some(entry)=history.down(){replace(&mut command,&mut length,entry)}}}unsafe{core::arch::asm!("sti","hlt",options(nomem,nostack))}}}
fn replace(command:&mut[u8;COMMAND_CAPACITY],length:&mut usize,entry:HistoryEntry){while*length>0{*length-=1;framebuffer::write_byte(8)}command.fill(0);command[..entry.length].copy_from_slice(&entry.data[..entry.length]);*length=entry.length;for&byte in&command[..*length]{framebuffer::write_byte(byte)}}
fn accent(){framebuffer::set_color(0x36,0xc5,0xf0)}fn banner(){framebuffer::clear_console();accent();framebuffer::write_line("ALOHAOS SHELL");framebuffer::set_color(0xd7,0xe0,0xee);framebuffer::write_line(if fat32::is_mounted(){"VIRTIO BLOCK FAT32 READY"}else{"DISK NOT MOUNTED"});framebuffer::write_line(if scheduler::context_switching_ready(){"ROUND ROBIN ACTIVE"}else{"ROUND ROBIN GATED"});framebuffer::write_line("TYPE HELP FOR COMMANDS");framebuffer::write_line("");prompt()}fn prompt(){accent();framebuffer::write_text("ALOHA> ");framebuffer::set_color(255,255,255)}
fn execute(raw:&[u8]){let command=trim(raw);if command==b"help"{framebuffer::write_line("HELP CLEAR MEMINFO UPTIME TASKS SCHED ON|OFF LS CAT STAT SPAWN REBOOT")}else if command==b"clear"{framebuffer::clear_console();accent();framebuffer::write_line("ALOHAOS SHELL")}else if command==b"meminfo"{meminfo()}else if command==b"uptime"{framebuffer::write_label_dec("UPTIME SECONDS: ",timer::seconds())}else if command==b"tasks"{tasks()}else if command==b"sched on"{if scheduler::set_preemption(true){framebuffer::write_line("ROUND ROBIN ENABLED")}else{framebuffer::write_line("ROUND ROBIN NOT READY")}}else if command==b"sched off"{if scheduler::set_preemption(false){framebuffer::write_line("ROUND ROBIN DISABLED")}else{framebuffer::write_line("DISABLE REJECTED")}}else if command==b"ls"||command==b"ls /"{fat32::list_root()}else if command.starts_with(b"cat "){fat32::cat(trim(&command[4..]))}else if command.starts_with(b"stat "){stat_file(trim(&command[5..]))}else if command.starts_with(b"spawn "){spawn_file(trim(&command[6..]))}else if command==b"reboot"{framebuffer::write_line("REBOOTING");pic::reboot()}else if command.is_empty(){}else{framebuffer::set_color(255,0x80,0x80);framebuffer::write_line("UNKNOWN COMMAND");framebuffer::set_color(255,255,255)}}
fn stat_file(name:&[u8]){match fat32::lookup(name){Some(location)=>framebuffer::write_label_dec("FILE SIZE: ",location.size as u64),None=>framebuffer::write_line("FILE NOT FOUND")}}
fn spawn_file(name:&[u8]){let Some(location)=fat32::lookup(name)else{framebuffer::write_line("FILE NOT FOUND");return};if location.size as usize>MAX_SHELL_IMAGE{framebuffer::write_line("ELF TOO LARGE");return}let mut image=[0u8;MAX_SHELL_IMAGE];let read=fat32::read_at(&location,0,&mut image[..location.size as usize]);if read!=location.size as usize{framebuffer::write_line("FILE READ FAILED");return}match spawn::spawn_elf(None,&image[..read]){Ok(mut child)=>{let pid=child.pid;framebuffer::write_label_dec("SPAWNED PID: ",pid);let _=user_mode::run(&mut child);framebuffer::write_label_dec("EXIT CODE: ",child.exit_code as u64);let _=process_table::remove(pid)}Err(_)=>framebuffer::write_line("SPAWN FAILED")}}
fn tasks(){for task in scheduler::snapshots(){framebuffer::write_label_dec("TASK ID: ",task.id as u64);framebuffer::write_line(match task.state{scheduler::TaskState::Ready=>"STATE READY",scheduler::TaskState::Running=>"STATE RUNNING",scheduler::TaskState::Blocked=>"STATE BLOCKED",scheduler::TaskState::Sleeping=>"STATE SLEEPING",scheduler::TaskState::Dead=>"STATE DEAD"});framebuffer::write_label_dec("CONTEXT SWITCHES: ",task.switches);if let Some(wake)=task.wake_tick{framebuffer::write_label_dec("WAKE TICK: ",wake)}}framebuffer::write_label_dec("WORKER HEARTBEAT: ",scheduler::worker_heartbeat());framebuffer::write_line(if scheduler::context_switching_ready(){"XSAVE CONTEXT SWITCH ACTIVE"}else{"XSAVE CONTEXT SWITCH GATED"})}
fn meminfo(){let frames=memory::stats();let heap=heap::stats();framebuffer::write_label_dec("PHYSICAL FREE KB: ",frames.free*4);framebuffer::write_label_dec("HEAP USED BYTES: ",heap.used as u64);framebuffer::write_label_dec("HEAP FREE BYTES: ",heap.free as u64);framebuffer::write_line(if virtio_blk::is_ready(){"VIRTIO BLOCK READY"}else{"VIRTIO BLOCK OFFLINE"});framebuffer::write_line(if fat32::is_mounted(){"FAT32 MOUNTED"}else{"FAT32 NOT MOUNTED"})}
fn trim(mut value:&[u8])->&[u8]{while value.first()==Some(&b' '){value=&value[1..]}while value.last()==Some(&b' '){value=&value[..value.len()-1]}value}
