//! Feature-gated smoke checks executed by headless QEMU CI.
use alloc::{boxed::Box,string::String,vec::Vec};use core::arch::asm;use crate::{address_space,elf,gdt,heap,keyboard,memory,process,process_table,serial,syscall,syscall_arch,syscall_entry};
#[cfg(feature="m0-smoke")]pub fn run_nonfatal(){heap_smoke();frame_smoke();keyboard_smoke();descriptor_smoke();process_smoke();syscall_smoke();elf_smoke();table_and_lifecycle_syscall_smoke();serial::info(format_args!("m0-smoke: heap keyboard memory passed"));}
#[cfg(not(feature="m0-smoke"))]pub fn run_nonfatal(){}
#[cfg(feature="m0-smoke")]fn heap_smoke(){let before=heap::stats();let b=Box::new(0xa10a05u64);let v=Vec::from([3u64,5,8,13]);let s=String::from("ALOHA-M0");assert_eq!(*b,0xa10a05);assert_eq!(v.iter().sum::<u64>(),29);assert_eq!(s.as_bytes(),b"ALOHA-M0");assert!(heap::stats().used>before.used);drop((b,v,s));serial::info(format_args!("m0-smoke: heap passed"));}
#[cfg(feature="m0-smoke")]fn frame_smoke(){let f=memory::allocate_frame().unwrap();assert!(unsafe{memory::deallocate_frame(f)});assert_eq!(memory::allocate_frame().unwrap(),f);serial::info(format_args!("m0-smoke: frame reclamation passed"));}
#[cfg(feature="m0-smoke")]fn keyboard_smoke(){keyboard::reset_decoder_for_smoke();assert!(matches!(keyboard::decode(0x10),Some(keyboard::Key::Character(b'q'))));serial::info(format_args!("m0-smoke: keyboard decode passed"));}
#[cfg(feature="m0-smoke")]fn descriptor_smoke(){assert_eq!(gdt::user_data_selector(),0x1b);assert_ne!(gdt::rsp0(),0);}
#[cfg(feature="m0-smoke")]fn process_smoke(){let before=memory::stats().allocated;let mut p=process::Process::new(7).unwrap();let data=p.user_stack_top-memory::FRAME_SIZE;p.address_space.copy_to_user(data,b"ALOHA").unwrap();let mut out=[0;5];p.address_space.copy_from_user(&mut out,data).unwrap();assert_eq!(&out,b"ALOHA");assert_eq!(p.address_space.copy_to_user(p.entry,b"X"),Err(address_space::UserAccessError::NotWritable));p.exit(42);drop(p);assert_eq!(memory::stats().allocated,before);}
#[cfg(feature="m0-smoke")]fn syscall_smoke(){let mut p=process::Process::new(9).unwrap();let data=p.user_stack_top-memory::FRAME_SIZE;p.address_space.copy_to_user(data,b"syscall").unwrap();assert_eq!(syscall::dispatch(&mut p,syscall::SYS_WRITE,[data,7,0,0,0,0]).value,7);let f=syscall_entry::UserReturnFrame{rip:process::USER_CODE_BASE,rsp:process::USER_STACK_TOP-16,rflags:0x202};assert_eq!(f.return_path(),syscall_entry::ReturnPath::Sysret);assert!(syscall_arch::configuration_valid());}
#[cfg(feature="m0-smoke")]fn elf_smoke(){let image=elf::test_image();let mut p=process::Process::new(12).unwrap();p.load_elf(&image).unwrap();let mut bytes=[0u8;32];p.address_space.copy_from_user(&mut bytes,p.entry).unwrap();assert_eq!(&bytes[..13],&image[120..133]);assert_eq!(&bytes[13..],[0u8;19]);}
#[cfg(feature="m0-smoke")]fn table_and_lifecycle_syscall_smoke(){process_table::reset_for_smoke();process_table::register(20,None).unwrap();let child=process_table::spawn(Some(20)).unwrap();let mut parent=process::Process::new(20).unwrap();let mut child_process=process::Process::new(child).unwrap();assert_eq!(syscall::dispatch(&mut parent,syscall::SYS_GETPID,[0;6]).value,20);assert_eq!(syscall::dispatch(&mut parent,syscall::SYS_WAIT,[child,0,0,0,0,0]).value,syscall::Errno::Busy.encoded());assert_eq!(syscall::dispatch(&mut child_process,syscall::SYS_SLEEP,[5,0,0,0,0,0]).value,0);assert_eq!(process_table::lookup(child).unwrap().state,process::ProcessState::Sleeping);let exit=syscall::dispatch(&mut child_process,syscall::SYS_EXIT,[91,0,0,0,0,0]);assert!(exit.terminated);assert_eq!(process_table::lookup(child).unwrap().exit_code,91);assert_eq!(syscall::dispatch(&mut parent,syscall::SYS_WAIT,[child,0,0,0,0,0]).value,91);assert!(process_table::lookup(child).is_none());serial::info(format_args!("m1-smoke: process lifecycle getpid sleep exit wait passed"));}
#[cfg(feature="ring3-smoke")]pub fn run_ring3()->!{const M:u32=0xa10a0033;let image=[0xb8,(M&255)as u8,((M>>8)&255)as u8,((M>>16)&255)as u8,((M>>24)&255)as u8,0xcd,0x80,0x0f,0x0b];let mut p=process::Process::new(33).unwrap();assert!(p.load_bootstrap_image(&image));serial::info(format_args!("ring3-smoke: entering user mode"));assert_eq!(crate::user_mode::run(&mut p),M as u64);serial::info(format_args!("ring3-smoke: user iretq rsp0 trap passed"));crate::halt()}
#[cfg(feature="syscall-smoke")]pub fn run_syscall()->!{let mut p=process::Process::new(44).unwrap();let msg=p.user_stack_top-memory::FRAME_SIZE;p.address_space.copy_to_user(msg,b"SYSCALL").unwrap();let mut image=[0u8;36];let mut i=0;macro_rules! e{($($b:expr),*$(,)?)=>{$(image[i]=$b;i+=1;)*};}e!(0xb8,1,0,0,0,0x48,0xbf);for b in msg.to_le_bytes(){image[i]=b;i+=1;}e!(0xbe,7,0,0,0,0x0f,0x05,0xb8,2,0,0,0,0xbf,42,0,0,0,0x0f,0x05,0x0f,0x0b);assert!(p.load_bootstrap_image(&image));serial::info(format_args!("syscall-smoke: entering real syscall path"));crate::user_mode::run(&mut p);assert_eq!(p.exit_code,42);serial::info(format_args!("syscall-smoke: write and exit passed"));crate::halt()}
#[cfg(feature="elf-smoke")]pub fn run_elf()->!{let image=elf::test_image();let mut p=process::Process::new(55).unwrap();p.load_elf(&image).unwrap();serial::info(format_args!("elf-smoke: entering loaded ELF"));crate::user_mode::run(&mut p);assert_eq!(p.exit_code,37);serial::info(format_args!("elf-smoke: loaded ELF syscall exit passed"));crate::halt()}
#[cfg(feature="exception-smoke")]pub fn trigger_exception()->!{serial::info(format_args!("exception-smoke: triggering breakpoint"));unsafe{asm!("int3",options(nomem,nostack))};panic!("breakpoint handler returned")}
#[cfg(not(feature="exception-smoke"))]pub fn trigger_exception(){}
