//! Feature-gated smoke checks executed by headless QEMU CI.
use alloc::{boxed::Box,string::String,vec::Vec};use core::arch::asm;use crate::{address_space,elf,gdt,heap,keyboard,memory,process,process_runtime,process_table,serial,syscall,syscall_arch,syscall_entry};
#[cfg(feature="m0-smoke")]pub fn run_nonfatal(){basic_smoke();process_runner_smoke();serial::info(format_args!("m0-smoke: heap keyboard memory passed"));}
#[cfg(not(feature="m0-smoke"))]pub fn run_nonfatal(){}
#[cfg(feature="m0-smoke")]fn basic_smoke(){let before=heap::stats();let b=Box::new(0xa10a05u64);let v=Vec::from([3u64,5,8,13]);let s=String::from("ALOHA-M0");assert_eq!(*b,0xa10a05);assert_eq!(v.iter().sum::<u64>(),29);assert_eq!(s.as_bytes(),b"ALOHA-M0");assert!(heap::stats().used>before.used);drop((b,v,s));serial::info(format_args!("m0-smoke: heap passed"));let f=memory::allocate_frame().unwrap();assert!(unsafe{memory::deallocate_frame(f)});assert_eq!(memory::allocate_frame().unwrap(),f);serial::info(format_args!("m0-smoke: frame reclamation passed"));keyboard::reset_decoder_for_smoke();assert!(matches!(keyboard::decode(0x10),Some(keyboard::Key::Character(b'q'))));serial::info(format_args!("m0-smoke: keyboard decode passed"));assert_eq!(gdt::user_data_selector(),0x1b);let mut p=process::Process::new(7).unwrap();let d=p.user_stack_top-memory::FRAME_SIZE;p.address_space.copy_to_user(d,b"ALOHA").unwrap();let mut out=[0;5];p.address_space.copy_from_user(&mut out,d).unwrap();assert_eq!(&out,b"ALOHA");assert_eq!(p.address_space.copy_to_user(p.entry,b"X"),Err(address_space::UserAccessError::NotWritable));let image=elf::test_image();p.load_elf(&image).unwrap();let frame=syscall_entry::UserReturnFrame{rip:p.entry,rsp:p.user_stack_top-16,rflags:0x202};assert_eq!(frame.return_path(),syscall_entry::ReturnPath::Sysret);assert!(syscall_arch::configuration_valid());}
#[cfg(feature="m0-smoke")]fn process_runner_smoke(){process_table::reset_for_smoke();process_table::register(40,None).unwrap();let mut p=process::Process::new(40).unwrap();assert_eq!(syscall::dispatch(&mut p,syscall::SYS_SLEEP,[5,100,0,0,0,0]).value,105);assert_eq!(process_runtime::on_timer_tick(105).sleepers_woken,1);assert!(process_runtime::reconcile(&mut p));serial::info(format_args!("m1-smoke: PIT sleep and blocking wait resume passed"));}
#[cfg(any(feature="user-ud-smoke",feature="user-nx-smoke",feature="user-write-code-smoke",feature="user-stack-guard-smoke"))]fn finish_fault_smoke(mut p:process::Process,vector:u64,label:&str)->!{process_table::reset_for_smoke();process_table::register(p.pid,None).unwrap();serial::info(format_args!("{}: entering user mode",label));assert_eq!(crate::user_mode::run(&mut p),u64::MAX);assert_eq!(p.state,process::ProcessState::Faulted);assert_eq!(process_table::lookup(p.pid).unwrap().exit_code,-(vector as i32));serial::info(format_args!("{}: process fault isolated",label));crate::halt()}
#[cfg(feature="user-ud-smoke")]pub fn run_user_ud()->!{let mut p=process::Process::new(61).unwrap();assert!(p.load_bootstrap_image(&[0x0f,0x0b]));finish_fault_smoke(p,6,"user-ud-smoke")}
#[cfg(feature="user-nx-smoke")]pub fn run_user_nx()->!{let mut p=process::Process::new(62).unwrap();p.entry=p.user_stack_top-memory::FRAME_SIZE;finish_fault_smoke(p,14,"user-nx-smoke")}
#[cfg(feature="user-write-code-smoke")]pub fn run_user_write_code()->!{let mut p=process::Process::new(63).unwrap();let target=p.entry.to_le_bytes();let mut image=[0u8;14];image[..2].copy_from_slice(&[0x48,0xb8]);image[2..10].copy_from_slice(&target);image[10..14].copy_from_slice(&[0xc6,0x00,0x90,0x0f]);assert!(p.load_bootstrap_image(&image));finish_fault_smoke(p,14,"user-write-code-smoke")}
#[cfg(feature="user-stack-guard-smoke")]pub fn run_user_stack_guard()->!{let mut p=process::Process::new(64).unwrap();let guard=(p.user_stack_top-5*memory::FRAME_SIZE).to_le_bytes();let mut image=[0u8;14];image[..2].copy_from_slice(&[0x48,0xb8]);image[2..10].copy_from_slice(&guard);image[10..14].copy_from_slice(&[0xc6,0x00,1,0x0f]);assert!(p.load_bootstrap_image(&image));finish_fault_smoke(p,14,"user-stack-guard-smoke")}
#[cfg(feature="user-bad-pointer-smoke")]pub fn run_user_bad_pointer()->!{let mut p=process::Process::new(65).unwrap();let invalid=(address_space::USER_REGION_START+0x40_0000).to_le_bytes();let mut image=[0u8;42];let mut i=0;macro_rules! e{($($b:expr),*$(,)?)=>{$(image[i]=$b;i+=1;)*};}e!(0xb8,1,0,0,0,0x48,0xbf);for b in invalid{image[i]=b;i+=1;}e!(0xbe,4,0,0,0,0x0f,0x05,0x48,0x83,0xf8,0xfe,0x75,0x0c,0xb8,2,0,0,0,0xbf,0,0,0,0,0x0f,0x05,0x0f,0x0b);assert_eq!(i,image.len());assert!(p.load_bootstrap_image(&image));serial::info(format_args!("user-bad-pointer-smoke: entering user mode"));crate::user_mode::run(&mut p);assert_eq!(p.state,process::ProcessState::Exited);assert_eq!(p.exit_code,0);serial::info(format_args!("user-bad-pointer-smoke: EFAULT returned without kernel fault"));crate::halt()}
#[cfg(feature="ring3-smoke")]pub fn run_ring3()->!{const M:u32=0xa10a0033;let image=[0xb8,(M&255)as u8,((M>>8)&255)as u8,((M>>16)&255)as u8,((M>>24)&255)as u8,0xcd,0x80,0x0f,0x0b];let mut p=process::Process::new(33).unwrap();assert!(p.load_bootstrap_image(&image));serial::info(format_args!("ring3-smoke: entering user mode"));assert_eq!(crate::user_mode::run(&mut p),M as u64);serial::info(format_args!("ring3-smoke: user iretq rsp0 trap passed"));crate::halt()}
#[cfg(feature="syscall-smoke")]pub fn run_syscall()->!{let mut p=process::Process::new(44).unwrap();let msg=p.user_stack_top-memory::FRAME_SIZE;p.address_space.copy_to_user(msg,b"SYSCALL").unwrap();let mut image=[0u8;36];let mut i=0;macro_rules! e{($($b:expr),*$(,)?)=>{$(image[i]=$b;i+=1;)*};}e!(0xb8,1,0,0,0,0x48,0xbf);for b in msg.to_le_bytes(){image[i]=b;i+=1;}e!(0xbe,7,0,0,0,0x0f,0x05,0xb8,2,0,0,0,0xbf,42,0,0,0,0x0f,0x05,0x0f,0x0b);assert!(p.load_bootstrap_image(&image));serial::info(format_args!("syscall-smoke: entering real syscall path"));crate::user_mode::run(&mut p);assert_eq!(p.exit_code,42);serial::info(format_args!("syscall-smoke: write and exit passed"));crate::halt()}
#[cfg(feature="elf-smoke")]pub fn run_elf()->!{let image=elf::test_image();let mut p=process::Process::new(55).unwrap();p.load_elf(&image).unwrap();serial::info(format_args!("elf-smoke: entering loaded ELF"));crate::user_mode::run(&mut p);assert_eq!(p.exit_code,37);serial::info(format_args!("elf-smoke: loaded ELF syscall exit passed"));crate::halt()}
#[cfg(feature="exception-smoke")]pub fn trigger_exception()->!{serial::info(format_args!("exception-smoke: triggering breakpoint"));unsafe{asm!("int3",options(nomem,nostack))};panic!("breakpoint handler returned")}
#[cfg(not(feature="exception-smoke"))]pub fn trigger_exception(){}
