//! Supervisor-owned child processes and atomic path-based spawn.
use alloc::vec::Vec;
use crate::{fat32,process::{Process,ProcessState},process_table,spawn::{self,SpawnError},sync::IrqSpinLock,user_mode};
const MAX_CHILDREN:usize=32;const MAX_IMAGE_SIZE:usize=256*1024;
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum SupervisorError{NotMounted,NoSuchFile,ImageTooLarge,ReadFailed,OutOfMemory,Capacity,NoSuchProcess,Spawn(SpawnError)}
impl From<SpawnError> for SupervisorError{fn from(value:SpawnError)->Self{Self::Spawn(value)}}
static CHILDREN:IrqSpinLock<Vec<Process>>=IrqSpinLock::new(Vec::new());
pub fn spawn_path(parent:u64,path:&[u8])->Result<u64,SupervisorError>{if !fat32::is_mounted(){return Err(SupervisorError::NotMounted)}let location=fat32::lookup(path).ok_or(SupervisorError::NoSuchFile)?;let image_size=location.size as usize;if image_size==0||image_size>MAX_IMAGE_SIZE{return Err(SupervisorError::ImageTooLarge)}{let mut children=CHILDREN.lock();if children.len()>=MAX_CHILDREN{return Err(SupervisorError::Capacity)}children.try_reserve(1).map_err(|_|SupervisorError::OutOfMemory)?;}let mut image=Vec::new();image.try_reserve_exact(image_size).map_err(|_|SupervisorError::OutOfMemory)?;image.resize(image_size,0);if fat32::read_at(&location,0,&mut image)!=image_size{return Err(SupervisorError::ReadFailed)}let child=spawn::spawn_elf((parent!=0).then_some(parent),&image)?;let pid=child.pid;let mut children=CHILDREN.lock();if children.len()>=MAX_CHILDREN{drop(children);let _=process_table::remove(pid);drop(child);return Err(SupervisorError::Capacity)}children.push(child);Ok(pid)}
pub fn take(pid:u64)->Option<Process>{let mut children=CHILDREN.lock();let index=children.iter().position(|process|process.pid==pid)?;Some(children.swap_remove(index))}
pub fn put(process:Process)->Result<(),SupervisorError>{let mut children=CHILDREN.lock();if children.len()>=MAX_CHILDREN{return Err(SupervisorError::Capacity)}children.try_reserve(1).map_err(|_|SupervisorError::OutOfMemory)?;children.push(process);Ok(())}
pub fn run(pid:u64)->Result<ProcessState,SupervisorError>{let mut process=take(pid).ok_or(SupervisorError::NoSuchProcess)?;let _=user_mode::run(&mut process);let state=process.state;if matches!(state,ProcessState::Ready|ProcessState::Running|ProcessState::Sleeping){put(process)?}Ok(state)}
pub fn run_one_child(parent:u64)->Result<ProcessState,SupervisorError>{let pid={let children=CHILDREN.lock();children.iter().find(|process|process_table::lookup(process.pid).map(|record|record.parent==parent).unwrap_or(false)).map(|process|process.pid)}.ok_or(SupervisorError::NoSuchProcess)?;run(pid)}
