//! Versioned syscall ABI and safe Rust dispatcher.

use crate::{address_space::MapError, fat32, handle::HandleError, process::{Process, ProcessState, SuspendedCall}, process_table, serial};

pub const ABI_VERSION:u64=1;pub const SYS_WRITE:u64=1;pub const SYS_EXIT:u64=2;pub const SYS_SLEEP:u64=3;pub const SYS_WAIT:u64=4;pub const SYS_GETPID:u64=5;pub const SYS_OPEN:u64=6;pub const SYS_READ:u64=7;pub const SYS_CLOSE:u64=8;pub const SYS_STAT:u64=9;pub const SYS_MMAP:u64=10;
pub const PROT_READ:u64=1;pub const PROT_WRITE:u64=2;pub const PROT_EXEC:u64=4;pub const MAP_ANONYMOUS:u64=1;
const MAX_WRITE:usize=256;const MAX_READ:usize=256;const MAX_PATH:usize=64;
#[derive(Clone,Copy,Debug,PartialEq,Eq)]#[repr(i64)]pub enum Errno{Invalid=1,BadAddress=2,TooLarge=3,NotSupported=4,NoSuchProcess=5,NotChild=6,Busy=7,NoSuchFile=8,BadHandle=9,TooManyOpen=10,OutOfMemory=11}
impl Errno{pub const fn encoded(self)->u64{(-(self as i64))as u64}}
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum SyscallAction{Return,Terminate,Suspend(SuspendedCall)}
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub struct SyscallResult{pub value:u64,pub action:SyscallAction}
impl SyscallResult{const fn ok(value:u64)->Self{Self{value,action:SyscallAction::Return}}const fn error(error:Errno)->Self{Self{value:error.encoded(),action:SyscallAction::Return}}const fn suspend(call:SuspendedCall)->Self{Self{value:0,action:SyscallAction::Suspend(call)}}}
pub fn dispatch(process:&mut Process,number:u64,args:[u64;6])->SyscallResult{match number{SYS_WRITE=>write(process,args[0],args[1]),SYS_EXIT=>{let code=args[0]as i32;process.exit(code);let _=process_table::exit(process.pid,code);process_table::orphan_children(process.pid);SyscallResult{value:0,action:SyscallAction::Terminate}},SYS_SLEEP=>{let now=args[1];let Some(deadline)=now.checked_add(args[0])else{return SyscallResult::error(Errno::Invalid)};if process_table::sleep_until(process.pid,now,deadline).is_err(){return SyscallResult::error(Errno::Invalid)}process.state=ProcessState::Sleeping;SyscallResult::suspend(SuspendedCall::Sleep)},SYS_WAIT=>match process_table::wait_blocking(process.pid,args[0]){Ok(Some(status))=>SyscallResult::ok(status as u32 as u64),Ok(None)=>{process.state=ProcessState::Sleeping;SyscallResult::suspend(SuspendedCall::Wait{child:args[0]})},Err(error)=>SyscallResult::error(table_errno(error))},SYS_GETPID=>SyscallResult::ok(process.pid),SYS_OPEN=>open(process,args[0],args[1]),SYS_READ=>read(process,args[0],args[1],args[2]),SYS_CLOSE=>close(process,args[0]),SYS_STAT=>stat(process,args[0],args[1],args[2]),SYS_MMAP=>mmap(process,args[0],args[1],args[2],args[3]),_=>SyscallResult::error(Errno::NotSupported)}}
fn table_errno(error:process_table::TableError)->Errno{match error{process_table::TableError::NoSuchProcess=>Errno::NoSuchProcess,process_table::TableError::NotChild=>Errno::NotChild,process_table::TableError::StillRunning=>Errno::Busy,process_table::TableError::Full|process_table::TableError::AlreadyExists|process_table::TableError::InvalidDeadline=>Errno::Invalid}}
fn handle_errno(error:HandleError)->Errno{match error{HandleError::NotMounted=>Errno::NotSupported,HandleError::NotFound=>Errno::NoSuchFile,HandleError::TooManyOpen=>Errno::TooManyOpen,HandleError::BadHandle=>Errno::BadHandle}}
fn map_errno(error:MapError)->Errno{match error{MapError::InvalidAddress|MapError::AlreadyMapped=>Errno::Invalid,MapError::OutOfFrames|MapError::OwnershipLimit=>Errno::OutOfMemory}}
fn write(process:&Process,address:u64,length:u64)->SyscallResult{let Ok(length)=usize::try_from(length)else{return SyscallResult::error(Errno::TooLarge)};if length>MAX_WRITE{return SyscallResult::error(Errno::TooLarge)}let mut buffer=[0u8;MAX_WRITE];if process.address_space.copy_from_user(&mut buffer[..length],address).is_err(){return SyscallResult::error(Errno::BadAddress)}serial::info(format_args!("user[{}] write {} bytes",process.pid,length));for chunk in buffer[..length].chunks(32){if let Ok(text)=core::str::from_utf8(chunk){serial::info(format_args!("user: {}",text))}else{serial::info(format_args!("user: <binary {} bytes>",chunk.len()))}}SyscallResult::ok(length as u64)}
fn read_path(process:&Process,address:u64,length:u64)->Result<([u8;MAX_PATH],usize),SyscallResult>{let Ok(length)=usize::try_from(length)else{return Err(SyscallResult::error(Errno::Invalid))};if length==0||length>MAX_PATH{return Err(SyscallResult::error(Errno::Invalid))}let mut path=[0u8;MAX_PATH];if process.address_space.copy_from_user(&mut path[..length],address).is_err(){return Err(SyscallResult::error(Errno::BadAddress))}Ok((path,length))}
fn open(process:&mut Process,address:u64,length:u64)->SyscallResult{let(path,length)=match read_path(process,address,length){Ok(value)=>value,Err(error)=>return error};match process.handle_table.open(&path[..length]){Ok(fd)=>SyscallResult::ok(fd as u64),Err(error)=>SyscallResult::error(handle_errno(error))}}
fn read(process:&mut Process,fd:u64,address:u64,length:u64)->SyscallResult{let Ok(fd)=usize::try_from(fd)else{return SyscallResult::error(Errno::BadHandle)};let Ok(length)=usize::try_from(length)else{return SyscallResult::error(Errno::TooLarge)};let length=length.min(MAX_READ);let mut buffer=[0u8;MAX_READ];let read=match process.handle_table.read(fd,&mut buffer[..length]){Ok(read)=>read,Err(error)=>return SyscallResult::error(handle_errno(error))};if read>0&&process.address_space.copy_to_user(address,&buffer[..read]).is_err(){return SyscallResult::error(Errno::BadAddress)}SyscallResult::ok(read as u64)}
fn close(process:&mut Process,fd:u64)->SyscallResult{let Ok(fd)=usize::try_from(fd)else{return SyscallResult::error(Errno::BadHandle)};match process.handle_table.close(fd){Ok(())=>SyscallResult::ok(0),Err(error)=>SyscallResult::error(handle_errno(error))}}
fn stat(process:&Process,address:u64,length:u64,stat_out:u64)->SyscallResult{let(path,length)=match read_path(process,address,length){Ok(value)=>value,Err(error)=>return error};let Some(location)=fat32::lookup(&path[..length])else{return SyscallResult::error(Errno::NoSuchFile)};if process.address_space.copy_to_user(stat_out,&(location.size as u64).to_le_bytes()).is_err(){return SyscallResult::error(Errno::BadAddress)}SyscallResult::ok(0)}
fn mmap(process:&mut Process,address:u64,length:u64,protection:u64,flags:u64)->SyscallResult{if address!=0||flags!=MAP_ANONYMOUS{return SyscallResult::error(Errno::NotSupported)}if protection&! (PROT_READ|PROT_WRITE|PROT_EXEC)!=0||protection&PROT_READ==0||protection&PROT_WRITE!=0&&protection&PROT_EXEC!=0{return SyscallResult::error(Errno::Invalid)}match process.map_anonymous(length,protection&PROT_WRITE!=0,protection&PROT_EXEC!=0){Ok(address)=>SyscallResult::ok(address),Err(error)=>SyscallResult::error(map_errno(error))}}
