//! Extended x86_64 task context: CR3, FS/GS and XSAVE state.
use core::arch::{asm,x86_64::__cpuid_count};use core::cell::UnsafeCell;use core::ptr;use core::sync::atomic::{AtomicBool,AtomicU64,Ordering};use crate::serial;
const TASK_COUNT:usize=2;const XSTATE_CAPACITY:usize=16*1024;const IA32_FS_BASE:u32=0xc000_0100;const IA32_GS_BASE:u32=0xc000_0101;
#[repr(C,align(64))]struct Xstate([u8;XSTATE_CAPACITY]);struct TaskContext{cr3:u64,fs_base:u64,gs_base:u64,xstate:Xstate}impl TaskContext{const EMPTY:Self=Self{cr3:0,fs_base:0,gs_base:0,xstate:Xstate([0;XSTATE_CAPACITY])};}
struct ContextSlots([UnsafeCell<TaskContext>;TASK_COUNT]);unsafe impl Sync for ContextSlots{}static CONTEXTS:ContextSlots=ContextSlots([UnsafeCell::new(TaskContext::EMPTY),UnsafeCell::new(TaskContext::EMPTY)]);static READY:AtomicBool=AtomicBool::new(false);static XCR0_MASK:AtomicU64=AtomicU64::new(0);
pub fn init()->bool{serial::debug(format_args!("context: cpuid"));let basic=__cpuid_count(1,0);if basic.ecx&(1<<26)==0{serial::error(format_args!("context: XSAVE unsupported"));return false}serial::debug(format_args!("context: enabling CR4 OSXSAVE"));unsafe{let mut cr4:u64;asm!("mov {}, cr4",out(reg)cr4,options(nomem,nostack,preserves_flags));cr4|=(1<<9)|(1<<10)|(1<<18);asm!("mov cr4, {}",in(reg)cr4,options(nostack,preserves_flags));}let supported=__cpuid_count(0x0d,0);let supported_mask=supported.eax as u64|((supported.edx as u64)<<32);let mut enabled=supported_mask&0b11;if enabled!=0b11{serial::error(format_args!("context: x87/SSE state unavailable"));return false}if basic.ecx&(1<<28)!=0&&supported_mask&(1<<2)!=0{enabled|=1<<2}serial::debug(format_args!("context: XSETBV mask {}",enabled));unsafe{xsetbv(enabled)};let configured=__cpuid_count(0x0d,0);serial::debug(format_args!("context: xstate bytes {}",configured.ebx));if configured.ebx as usize>XSTATE_CAPACITY{return false}XCR0_MASK.store(enabled,Ordering::Release);serial::debug(format_args!("context: initial XSAVE"));unsafe{save(0);ptr::copy_nonoverlapping(CONTEXTS.0[0].get(),CONTEXTS.0[1].get(),1)}READY.store(true,Ordering::Release);serial::info(format_args!("context: XSAVE ready"));true}
pub fn is_ready()->bool{READY.load(Ordering::Acquire)}pub fn xcr0_mask()->u64{XCR0_MASK.load(Ordering::Acquire)}pub unsafe fn switch(current:usize,next:usize){if current==next||!is_ready(){return}save(current);restore(next)}
unsafe fn save(task:usize){let c=&mut*CONTEXTS.0[task].get();c.cr3=read_cr3();c.fs_base=rdmsr(IA32_FS_BASE);c.gs_base=rdmsr(IA32_GS_BASE);let mask=XCR0_MASK.load(Ordering::Relaxed);asm!("xsave64 [{}]",in(reg)c.xstate.0.as_mut_ptr(),in("eax")mask as u32,in("edx")(mask>>32)as u32,options(nostack));}
unsafe fn restore(task:usize){let c=&*CONTEXTS.0[task].get();if read_cr3()!=c.cr3{asm!("mov cr3, {}",in(reg)c.cr3,options(nostack,preserves_flags));}wrmsr(IA32_FS_BASE,c.fs_base);wrmsr(IA32_GS_BASE,c.gs_base);let mask=XCR0_MASK.load(Ordering::Relaxed);asm!("xrstor64 [{}]",in(reg)c.xstate.0.as_ptr(),in("eax")mask as u32,in("edx")(mask>>32)as u32,options(nostack));}
#[inline]unsafe fn xsetbv(v:u64){asm!("xsetbv",in("ecx")0u32,in("eax")v as u32,in("edx")(v>>32)as u32,options(nostack));}#[inline]unsafe fn read_cr3()->u64{let v:u64;asm!("mov {}, cr3",out(reg)v,options(nomem,nostack,preserves_flags));v}#[inline]unsafe fn rdmsr(m:u32)->u64{let l:u32;let h:u32;asm!("rdmsr",in("ecx")m,out("eax")l,out("edx")h,options(nostack));l as u64|((h as u64)<<32)}#[inline]unsafe fn wrmsr(m:u32,v:u64){asm!("wrmsr",in("ecx")m,in("eax")v as u32,in("edx")(v>>32)as u32,options(nostack));}
